spring.application.name=pan-african-backend
server.port=${PORT:8081}

spring.profiles.active=dev
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL:jdbc:mysql://localhost:3306/pan_african?createDatabaseIfNotExist=true}}
spring.datasource.username=${DB_USER:pan_african}
spring.datasource.password=${DB_PASSWORD:pan_african_dev}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}